"""add ai columns to tickets

Revision ID: 6a19fa870187
Revises: 0959c9eeaa94
Create Date: 2026-06-17 11:31:29.703639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a19fa870187'
down_revision: Union[str, Sequence[str], None] = '0959c9eeaa94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('ai_category', sa.String(length=100), nullable=True))
    op.add_column('tickets', sa.Column('ai_priority', sa.String(length=50), nullable=True))
    op.add_column('tickets', sa.Column('ai_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'ai_summary')
    op.drop_column('tickets', 'ai_priority')
    op.drop_column('tickets', 'ai_category')
    # ### end Alembic commands ###
